src/main/java/org/projet/golf/rulesgenerator/models/Regle.java
package org.projet.golf.rulesgenerator.models;

import javax.persistence.*;
import java.util.Objects;

@Entity
public class Regle {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private Integer num;
    private String titre;

    @Column(length= 20000)
    private String contenu;

    @ManyToOne
    private SousCategorie sousCategorie;

    public Regle(){
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getNum() {
        return num;
    }

    public void setNum(Integer num) {
        this.num = num;
    }

    public String getTitre() {
        return titre;
    }

    public void setTitre(String titre) {
        this.titre = titre;
    }

    public String getContenu() {
        return contenu;
    }

    public void setContenu(String contenu) {
        this.contenu = contenu;
    }

    public SousCategorie getSousCategorie() {
        return sousCategorie;
    }

    public void setSousCategorie(SousCategorie sousCategorie) {
        this.sousCategorie = sousCategorie;
    }

    public String getCode() {
        return this.getSousCategorie().getCategorie().getCode()+'.'+this.getSousCategorie().getNum()+'.'+this.getNum();
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Regle)) return false;
        Regle regle = (Regle) o;
        return Objects.equals(getId(), regle.getId()) &&
                Objects.equals(getNum(), regle.getNum()) &&
                Objects.equals(getTitre(), regle.getTitre()) &&
                Objects.equals(getContenu(), regle.getContenu());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(), getNum(), getTitre(), getContenu());
    }
}

src/main/resources/templates/inscription.ftlh
<#import "main.ftlh" as m>
<@m.page title="">

    <div class="container-fluid">
        <h3></h3>
        <div><center>
                <form action="/Inscriptions" method="post">
                    <div class="container">
                        <h1>Inscription</h1>
                        <p>Bienvenue amateurs et professionnels de golf</p>
                        <br/>
                        <div class="inp">
                            <label for="email"><b>Nom : </b></label>
                            <input type="text" placeholder="Entrer votre Nom de famille" name="name" required>
                            <br/>
                        </div>
                        <div class="inp">
                        <label for="email"><b>Email : </b></label>
                        <input type="text" placeholder="Entrer votre Email" name="email" required>
                        <br/>
                        </div>
                        <div class="inp">
                        <label for="psw"><b>Mot de passe : </b></label>
                        <input type="password" placeholder="Minimum 12 caractères" name="psw" required>
                        <br/>
                        </div>
                        <div class="inp">
                        <label for="psw-repeat"><b>Répéter : </b></label>
                        <input type="password" placeholder="Répéter le mot de passe" name="psw-repeat">
                        <br>
                        </div>
                        <br/>
                        <p>En créant ce compte vous acceptez notre <a href="#">politique de confidentialité</a>.</p>
                        <button type="submit" class="registerbtn">Inscription</button>
                    </div>

                    <div class="container signin">
                        <p>Vous possedez déjà un compte ? <a href="/Connexion">Par ici</a>.</p>
                    </div>
                </form>
            </center></div>
    </div>

</@m.page>

src/main/resources/templates/rules.ftlh
<#import "main.ftlh" as m>
<@m.page title="">

    <div class="container">
        <h2>Règles locales</h2>
        <div class="accordeon">
            <form action="/Modifier" method="POST">
            <#list categories as categorie>
                <div class="card categorie">
                <div>
                    <a class="card-link" data-toggle="collapse" href="#cat${categorie.id}">
                        <li><b> ${categorie.code}</b> : ${categorie.titre}</a>
                    <a href="/Categorie/${categorie.id}" style="float: right"><button type="button" value="${categorie.id}">Modifier</button></a></li>
                </div>
            </form>

                </div>
                <br/>
                <#list categorie.getSousCategorieList() as soucat>
                <div class="collapse" id="cat${categorie.id}">
                    <!-- a fermer plustard == (balise collapse num 1)!!-->

                    <div>
                        <a class="card-link" data-toggle="collapse" href="#SouCat${soucat.id}"
                           value="${soucat.id}">
                        <li id="soucat"><b>${categorie.code}.${soucat.num}</b> : ${soucat.titre}</li></a>
                    </div>

                    <#list soucat.getRegles() as regle>
                        <div class="collapse show" id="SouCat${soucat.id}">
                            <!-- a fermer plustard == (balise collapse num 2)!!-->

                            <a class="card-link" data-toggle="collapse" href="#menuRegles${regle.id}" value="${regle.id}">

                            <label class="cont" for="${categorie.code}${categorie.id}${soucat.id}${regle.id}"></label>
                            <li><b>${categorie.code}.${soucat.num}.${regle.num}</b>: ${regle.titre!""}</li>
                            </a>
                            <input type="checkbox" id="${categorie.code}${categorie.id}${soucat.id}${regle.id}"
                                   value="${categorie.code}${categorie.id}${soucat.id}${regle.id}">
                            <span class="checkmark"></span>


                            <div class="collapse show regle" id="menuRegles${regle.id}" >
                                ${regle.contenu}
                            </div>
                            <br/>
                        </div> <!-- fermeture balise collapse num 2-->
                    </#list>
                </div> <!-- fermeture balise collapse num 1-->
                </#list>
            </#list>

        </div>  <!-- accordeon -->
    </div>  <!-- container-->
</@m.page>